### ISSUE TITLE
Add some documentation to the README

### ISSUE THREAD

**Issue by philippgille** [lightningj-org/paywall#1]
Hi, when someone recently said on Twitter that a cool Lightning project would be to create web framework plugins (middleware) that handle a paywall for specific routes, I pointed him to three projects that I knew of:
- For Express: https://github.com/ElementsProject/paypercall
- For Rack: https://github.com/bumi/rack-lightning
- For Go: https://github.com/philippgille/ln-paywall (my own)

I also found this repo, but on a short glimpse I only saw the Spring example directories and the "core" directory with its *many* subdirectories, but wasn't sure if there was a simple library to just set up a paywall middleware.

I think it would be really helpful if you would add some basic documentation to your README, like:
- What is contained in the repo
- How to add the library to a Spring Boot project to add a paywall to a route
- What else the library has to offer
- Links to above mentioned existing libraries for other programming languages / frameworks
- ...

You can check out my https://github.com/philippgille/ln-paywall for inspiration :)

**Comment by herrvendil** [comment]
Hi

I will in coming months add proper documentation for the project. The project became a lot larger than initially though so I had to take a pause but will soon try to finish a first working alpha version. Right now it isn't complete.

But my main idea is to create a spring project that makes it super easy to add paywall requirement by just adding an annotation @PaymentRequired to you @RestController. If you add it an invoice will be automatically created and a filter will manage the payment handling until the user is redirected back to the @RestController and the payment will succeed.

**Comment by philippgille** [comment]
Sounds great! Is there anything I might help you with? Maybe you can create issues for the remaining tasks, which makes it easier for other people to know how they can contribute.

And you could keep this issue open until the documentation is added and then automatically close it with a commit or PR message that contains `closes #1`. I think that's how most open source projects handle valid issues.

Looking forward to a Spring Boot LN paywall!

**Comment by herrvendil** [comment]
You are right, I shouldn't have closed the issue so fast. I'm currently working on getting lightningj to support the upcoming LND 0.6.0 APIs. And there are a lot of new features there so it will take some time. After that I will come back to this project and as soon as it is runnable I will update with documentation. Just give me a few weeks.

It would also be interesting to have some discussions about design decisions after documenting them since I'm far from certain I made the right ones.

**Comment by herrvendil** [comment]
Hi again, I have now updated the project with documentation. It is easies to read at https://paywall.lightningj.org/ but I have also written a Medium article for a little less techinal go through of the project: https://medium.com/@infolightningj/lightningj-paywall-bringing-micropayments-to-microservices-4c0123d14e8c
